-- DROP TABLES (Run this first to clear errors)
DROP TABLE ENROLLMENT CASCADE CONSTRAINTS;
DROP TABLE BEHAVIOR_LOG CASCADE CONSTRAINTS;
DROP TABLE STUDENT CASCADE CONSTRAINTS;
DROP TABLE COURSE CASCADE CONSTRAINTS;
DROP TABLE SCHOOL CASCADE CONSTRAINTS;

-- 1. SCHOOL
CREATE TABLE SCHOOL (
    School_Name VARCHAR2(100) PRIMARY KEY,
    School_Type CHAR(2) CHECK (School_Type IN ('GP', 'MS'))
);

-- 2. COURSE
CREATE TABLE COURSE (
    Course_Code VARCHAR2(10) PRIMARY KEY,
    Course_Name VARCHAR2(100) NOT NULL,
    Credits NUMBER NOT NULL
);

-- 3. STUDENT
CREATE TABLE STUDENT (
    Student_ID NUMBER PRIMARY KEY,
    First_Name VARCHAR2(50) NOT NULL,
    Last_Name VARCHAR2(50) NOT NULL,
    Age NUMBER,
    Address_Line_2 VARCHAR2(100),
    School_Name VARCHAR2(100),
    CONSTRAINT fk_school FOREIGN KEY (School_Name) REFERENCES SCHOOL(School_Name)
);

-- 4. ENROLLMENT
CREATE TABLE ENROLLMENT (
    Student_ID NUMBER,
    Course_Code VARCHAR2(10),
    G1 NUMBER,
    G2 NUMBER,
    G3 NUMBER,
    PRIMARY KEY (Student_ID, Course_Code),
    CONSTRAINT fk_std_enroll FOREIGN KEY (Student_ID) REFERENCES STUDENT(Student_ID),
    CONSTRAINT fk_crs_enroll FOREIGN KEY (Course_Code) REFERENCES COURSE(Course_Code)
);



-- 5. BEHAVIOR_LOG
CREATE TABLE BEHAVIOR_LOG (
    Student_ID NUMBER,
    Log_Date DATE,
    Workday_Alcohol NUMBER CHECK (Workday_Alcohol BETWEEN 1 AND 5),
    Weekend_Alcohol NUMBER CHECK (Weekend_Alcohol BETWEEN 1 AND 5),
    Health_Status NUMBER NOT NULL,
    PRIMARY KEY (Student_ID, Log_Date),
    CONSTRAINT fk_std_log FOREIGN KEY (Student_ID) REFERENCES STUDENT(Student_ID) ON DELETE CASCADE
);
-- DELETE FROM ENROLLMENT WHERE 1=1;
-- DELETE FROM BEHAVIOR_LOG WHERE 1=1;
-- DELETE FROM STUDENT WHERE 1=1;
-- COMMIT;

-- DELETE FROM ENROLLMENT WHERE 1=1;
-- DELETE FROM BEHAVIOR_LOG WHERE 1=1;
-- DELETE FROM STUDENT WHERE 1=1;
-- DELETE FROM COURSE WHERE 1=1;
-- DELETE FROM SCHOOL WHERE 1=1;
-- COMMIT;

SELECT s.First_Name, s.Last_Name, s.School_Name, e.Course_Code, e.G3
FROM STUDENT s
JOIN ENROLLMENT e ON s.Student_ID = e.Student_ID
ORDER BY e.G3 DESC;

SELECT b.Weekend_Alcohol, ROUND(AVG(e.G3), 2) as Avg_Final_Grade
FROM BEHAVIOR_LOG b
JOIN ENROLLMENT e ON b.Student_ID = e.Student_ID
GROUP BY b.Weekend_Alcohol
ORDER BY b.Weekend_Alcohol;